version: "3.8"
services:
  app:
    build: .
    volumes:
      - .:/django
    ports:
      - 8000:8000
    image: app:django
    container_name: chatbot
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - chatbot 
  chatbot:
    image: mysql:5.7
    environment:
      MYSQL_USER: nhuan
      MYSQL_PASSWORD: nt0329689087N
      MYSQL_ROOT_PASSWORD: nt0329689087N
      MYSQL_DATABASE: chatbot
    volumes:
      - ./data/mysql/db:/var/lib/mysql


